variable "grafana_auth" {

}

variable "grafana_url" {

}

variable "log_analytics_workspace_id" {
  default = ""
}


variable "subscription_id" {
  type = string

}

variable "default_location" {
  default = "germanywestcentral"
  type    = string
}

variable "root_name" {
  default     = "contoso"
  description = "value of the root management group name"
  type        = string
}

variable "tenant_id" {
  type = string
}

variable "parameters" {
  description = "values for the parameters for the policy assignments. The default are the default for each policy."
  default = {
    "Deploy-AMBA-HybridVM" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "ALZUserAssignedManagedIdentityName" : "id-AMBA-ARG-Reader-001",
      "ALZManagementSubscriptionId" : "",
      "BYOUserAssignedManagedIdentityResourceId" : "",
      "HybridVMHeartBeatRGAlertSeverity" : "1",
      "HybridVMHeartBeatRGWindowSize" : "PT15M",
      "HybridVMHeartBeatRGEvaluationFrequency" : "PT5M",
      "HybridVMHeartBeatRGAutoMitigate" : "true",
      "HybridVMHeartBeatRGAutoResolve" : "true",
      "HybridVMHeartBeatRGAutoResolveTime" : "00:10:00",
      "HybridVMHeartBeatRGPolicyEffect" : "deployIfNotExists",
      "HybridVMHeartBeatRGAlertState" : "true",
      "HybridVMHeartBeatRGThreshold" : "10",
      "HybridVMHeartBeatRGOperator" : "GreaterThan",
      "HybridVMHeartBeatRGTimeAggregation" : "Average",
      "HybridVMNetworkInAlertSeverity" : "2",
      "HybridVMNetworkInWindowSize" : "PT15M",
      "HybridVMNetworkInEvaluationFrequency" : "PT5M",
      "HybridVMNetworkInAutoMitigate" : "true",
      "HybridVMNetworkInAutoResolve" : "true",
      "HybridVMNetworkInAutoResolveTime" : "00:10:00",
      "HybridVMNetworkInPolicyEffect" : "deployIfNotExists",
      "HybridVMNetworkInAlertState" : "true",
      "HybridVMNetworkInThreshold" : "10000000",
      "HybridVMNetworkInOperator" : "GreaterThan",
      "HybridVMNetworkInTimeAggregation" : "Average",
      "HybridVMNetworkInEvaluationPeriods" : "1",
      "HybridVMNetworkInFailingPeriods" : "1",
      "HybridVMNetworkInComputersToInclude" : [
        "*"
      ],
      "HybridVMNetworkInNetworkInterfaceToInclude" : [
        "*"
      ],
      "HybridVMNetworkOutAlertSeverity" : "2",
      "HybridVMNetworkOutWindowSize" : "PT15M",
      "HybridVMNetworkOutEvaluationFrequency" : "PT5M",
      "HybridVMNetworkOutAutoMitigate" : "true",
      "HybridVMNetworkOutAutoResolve" : "true",
      "HybridVMNetworkOutAutoResolveTime" : "00:10:00",
      "HybridVMNetworkOutPolicyEffect" : "deployIfNotExists",
      "HybridVMNetworkOutAlertState" : "true",
      "HybridVMNetworkOutThreshold" : "10000000",
      "HybridVMNetworkOutOperator" : "GreaterThan",
      "HybridVMNetworkOutTimeAggregation" : "Average",
      "HybridVMNetworkOutEvaluationPeriods" : "1",
      "HybridVMNetworkOutFailingPeriods" : "1",
      "HybridVMNetworkOutComputersToInclude" : [
        "*"
      ],
      "HybridVMNetworkOutNetworkInterfaceToInclude" : [
        "*"
      ],
      "HybridVMOSDiskReadLatencyAlertSeverity" : "2",
      "HybridVMOSDiskReadLatencyWindowSize" : "PT15M",
      "HybridVMOSDiskReadLatencyEvaluationFrequency" : "PT5M",
      "HybridVMOSDiskReadLatencyAutoMitigate" : "true",
      "HybridVMOSDiskReadLatencyAutoResolve" : "true",
      "HybridVMOSDiskReadLatencyAutoResolveTime" : "00:10:00",
      "HybridVMOSDiskReadLatencyPolicyEffect" : "deployIfNotExists",
      "HybridVMOSDiskReadLatencyAlertState" : "true",
      "HybridVMOSDiskReadLatencyThreshold" : "30",
      "HybridVMOSDiskReadLatencyOperator" : "LessThan",
      "HybridVMOSDiskReadLatencyTimeAggregation" : "Average",
      "HybridVMOSDiskReadLatencyEvaluationPeriods" : "1",
      "HybridVMOSDiskReadLatencyFailingPeriods" : "1",
      "HybridVMOSDiskReadLatencyComputersToInclude" : [
        "*"
      ],
      "HybridVMOSDiskReadLatencyDisksToInclude" : [
        "C:",
        "/"
      ],
      "HybridVMOSDiskWriteLatencyAlertSeverity" : "2",
      "HybridVMOSDiskWriteLatencyWindowSize" : "PT15M",
      "HybridVMOSDiskWriteLatencyEvaluationFrequency" : "PT5M",
      "HybridVMOSDiskWriteLatencyAutoMitigate" : "true",
      "HybridVMOSDiskWriteLatencyAutoResolve" : "true",
      "HybridVMOSDiskWriteLatencyAutoResolveTime" : "00:10:00",
      "HybridVMOSDiskWriteLatencyPolicyEffect" : "deployIfNotExists",
      "HybridVMOSDiskWriteLatencyAlertState" : "true",
      "HybridVMOSDiskWriteLatencyThreshold" : "50",
      "HybridVMOSDiskWriteLatencyOperator" : "LessThan",
      "HybridVMOSDiskWriteLatencyTimeAggregation" : "Average",
      "HybridVMOSDiskWriteLatencyEvaluationPeriods" : "1",
      "HybridVMOSDiskWriteLatencyFailingPeriods" : "1",
      "HybridVMOSDiskWriteLatencyComputersToInclude" : [
        "*"
      ],
      "HybridVMOSDiskWriteLatencyDisksToInclude" : [
        "C:",
        "/"
      ],
      "HybridVMOSDiskSpaceAlertSeverity" : "2",
      "HybridVMOSDiskSpaceWindowSize" : "PT15M",
      "HybridVMOSDiskSpaceEvaluationFrequency" : "PT5M",
      "HybridVMOSDiskSpaceAutoMitigate" : "true",
      "HybridVMOSDiskSpaceAutoResolve" : "true",
      "HybridVMOSDiskSpaceAutoResolveTime" : "00:10:00",
      "HybridVMOSDiskSpacePolicyEffect" : "deployIfNotExists",
      "HybridVMOSDiskSpaceAlertState" : "true",
      "HybridVMOSDiskSpaceThreshold" : "10",
      "HybridVMOSDiskSpaceOperator" : "LessThan",
      "HybridVMOSDiskSpaceTimeAggregation" : "Average",
      "HybridVMOSDiskSpaceEvaluationPeriods" : "1",
      "HybridVMOSDiskSpaceFailingPeriods" : "1",
      "HybridVMOSDiskSpaceComputersToInclude" : [
        "*"
      ],
      "HybridVMOSDiskSpaceDisksToInclude" : [
        "C:",
        "/"
      ],
      "HybridVMPercentCPUAlertSeverity" : "2",
      "HybridVMPercentCPUWindowSize" : "PT15M",
      "HybridVMPercentCPUEvaluationFrequency" : "PT5M",
      "HybridVMPercentCPUAutoMitigate" : "true",
      "HybridVMPercentCPUAutoResolve" : "true",
      "HybridVMPercentCPUAutoResolveTime" : "00:10:00",
      "HybridVMPercentCPUPolicyEffect" : "deployIfNotExists",
      "HybridVMPercentCPUAlertState" : "true",
      "HybridVMPercentCPUThreshold" : "85",
      "HybridVMPercentCPUOperator" : "GreaterThan",
      "HybridVMPercentCPUTimeAggregation" : "Average",
      "HybridVMPercentMemoryAlertSeverity" : "2",
      "HybridVMPercentMemoryWindowSize" : "PT15M",
      "HybridVMPercentMemoryEvaluationFrequency" : "PT5M",
      "HybridVMPercentMemoryAutoMitigate" : "true",
      "HybridVMPercentMemoryAutoResolve" : "true",
      "HybridVMPercentMemoryAutoResolveTime" : "00:10:00",
      "HybridVMPercentMemoryPolicyEffect" : "deployIfNotExists",
      "HybridVMPercentMemoryAlertState" : "true",
      "HybridVMPercentMemoryThreshold" : "10",
      "HybridVMPercentMemoryOperator" : "LessThan",
      "HybridVMPercentMemoryTimeAggregation" : "Average",
      "HybridVMDataDiskSpaceAlertSeverity" : "2",
      "HybridVMDataDiskSpaceWindowSize" : "PT15M",
      "HybridVMDataDiskSpaceEvaluationFrequency" : "PT5M",
      "HybridVMDataDiskSpaceAutoMitigate" : "true",
      "HybridVMDataDiskSpaceAutoResolve" : "true",
      "HybridVMDataDiskSpaceAutoResolveTime" : "00:10:00",
      "HybridVMDataDiskSpacePolicyEffect" : "deployIfNotExists",
      "HybridVMDataDiskSpaceAlertState" : "true",
      "HybridVMDataDiskSpaceThreshold" : "10",
      "HybridVMDataDiskSpaceOperator" : "LessThan",
      "HybridVMDataDiskSpaceTimeAggregation" : "Average",
      "HybridVMDataDiskSpaceEvaluationPeriods" : "1",
      "HybridVMDataDiskSpaceFailingPeriods" : "1",
      "HybridVMDataDiskSpaceDisksToInclude" : [
        "*"
      ],
      "HybridVMDataDiskReadLatencyAlertSeverity" : "2",
      "HybridVMDataDiskReadLatencyWindowSize" : "PT15M",
      "HybridVMDataDiskReadLatencyEvaluationFrequency" : "PT5M",
      "HybridVMDataDiskReadLatencyAutoMitigate" : "true",
      "HybridVMDataDiskReadLatencyAutoResolve" : "true",
      "HybridVMDataDiskReadLatencyAutoResolveTime" : "00:10:00",
      "HybridVMDataDiskReadLatencyPolicyEffect" : "deployIfNotExists",
      "HybridVMDataDiskReadLatencyAlertState" : "true",
      "HybridVMDataDiskReadLatencyThreshold" : "30",
      "HybridVMDataDiskReadLatencyOperator" : "LessThan",
      "HybridVMDataDiskReadLatencyTimeAggregation" : "Average",
      "HybridVMDataDiskReadLatencyEvaluationPeriods" : "1",
      "HybridVMDataDiskReadLatencyFailingPeriods" : "1",
      "HybridVMDataDiskReadLatencyComputersToInclude" : [
        "*"
      ],
      "HybridVMDataDiskReadLatencyDisksToInclude" : [
        "*"
      ],
      "HybridVMDataDiskWriteLatencyAlertSeverity" : "2",
      "HybridVMDataDiskWriteLatencyWindowSize" : "PT15M",
      "HybridVMDataDiskWriteLatencyEvaluationFrequency" : "PT5M",
      "HybridVMDataDiskWriteLatencyAutoMitigate" : "true",
      "HybridVMDataDiskWriteLatencyAutoResolve" : "true",
      "HybridVMDataDiskWriteLatencyAutoResolveTime" : "00:10:00",
      "HybridVMDataDiskWriteLatencyPolicyEffect" : "deployIfNotExists",
      "HybridVMDataDiskWriteLatencyAlertState" : "true",
      "HybridVMDataDiskWriteLatencyThreshold" : "30",
      "HybridVMDataDiskWriteLatencyOperator" : "LessThan",
      "HybridVMDataDiskWriteLatencyTimeAggregation" : "Average",
      "HybridVMDataDiskWriteLatencyEvaluationPeriods" : "1",
      "HybridVMDataDiskWriteLatencyFailingPeriods" : "1",
      "HybridVMDataDiskWriteLatencyComputersToInclude" : [
        "*"
      ],
      "HybridVMDataDiskWriteLatencyDisksToInclude" : [
        "*"
      ],
      "HybridVMDisconnectedAlertSeverity" : "1",
      "HybridVMDisconnectedAlertWindowSize" : "P1D",
      "HybridVMDisconnectedAlertEvaluationFrequency" : "P1D",
      "HybridVMDisconnectedAlertAutoMitigate" : "true",
      "HybridVMDisconnectedAlertPolicyEffect" : "deployIfNotExists",
      "HybridVMDisconnectedAlertState" : "true",
      "HybridVMDisconnectedAlertDaysThreshold" : "45",
      "HybridVMDisconnectedAlertOperator" : "GreaterThanOrEqual",
      "HybridVMDisconnectedAlertTimeAggregation" : "Minimum",
      "HybridVMDisconnectedAlertEvaluationPeriods" : "1",
      "HybridVMDisconnectedAlertFailingPeriods" : "1"
    },
    "Deploy-AMBA-Management" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "AATotalJobAlertSeverity" : "2",
      "AATotalJobAlertWindowSize" : "PT5M",
      "AATotalJobAlertEvaluationFrequency" : "PT1M",
      "AATotalJobAlertPolicyEffect" : "deployIfNotExists",
      "AATotalJobAlertAlertState" : "true",
      "AATotalJobAlertThreshold" : "20",
      "RVBackupHealthMonitorPolicyEffect" : "modify",
      "StorageAccountAvailabilityAlertSeverity" : "1",
      "StorageAccountAvailabilityWindowSize" : "PT5M",
      "StorageAccountAvailabilityFrequency" : "PT5M",
      "StorageAccountAvailabilityPolicyEffect" : "deployIfNotExists",
      "StorageAccountAvailabilityAlertState" : "true",
      "StorageAccountAvailabilityThreshold" : "90",
      "StorageAccountDeletePolicyEffect" : "deployIfNotExists",
      "StorageAccountDeleteAlertState" : "true",
      "activityLAWDeleteAlertState" : "true",
      "activityLAWKeyRegenAlertState" : "true"
    },
    "Deploy-AMBA-SvcHealth" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "ResHlthUnhealthyAlertState" : "true",
      "ResHlthUnhealthyPolicyEffect" : "deployIfNotExists",
      "SvcHlthAdvisoryAlertState" : "true",
      "serviceHealthAdvisoryPolicyEffect" : "deployIfNotExists",
      "SvcHlthIncidentAlertState" : "true",
      "serviceHealthIncidentPolicyEffect" : "deployIfNotExists",
      "SvcHlthMaintenanceAlertState" : "true",
      "serviceHealthMaintenancePolicyEffect" : "deployIfNotExists",
      "svcHlthSecAdvisoryAlertState" : "true",
      "serviceHealthSecurityPolicyEffect" : "deployIfNotExists",
      "MonitorDisable" : "MonitorDisable",
      "ALZMonitorActionGroupEmail" : "",
      "ALZLogicappResourceId" : "",
      "ALZLogicappCallbackUrl" : "",
      "ALZArmRoleId" : "",
      "ALZEventHubResourceId" : "",
      "ALZWebhookServiceUri" : "",
      "ALZFunctionResourceId" : "",
      "ALZFunctionTriggerUrl" : "",
      "BYOActionGroup" : "",
      "BYOAlertProcessingRule" : ""
    },
    "Deploy-AMBA-Connectivity" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "ERCIRQoSDropBitsinPerSecAlertSeverity" : "2",
      "ERCIRQoSDropBitsinPerSecWindowSize" : "PT5M",
      "ERCIRQoSDropBitsinPerSecEvaluationFrequency" : "PT5M",
      "ERCIRQoSDropBitsinPerSecPolicyEffect" : "deployIfNotExists",
      "ERCIRQoSDropBitsinPerSecAlertState" : "true",
      "ERCIRQoSDropBitsoutPerSecAlertSeverity" : "2",
      "ERCIRQoSDropBitsoutPerSecWindowSize" : "PT5M",
      "ERCIRQoSDropBitsoutPerSecEvaluationFrequency" : "PT5M",
      "ERCIRQoSDropBitsoutPerSecPolicyEffect" : "deployIfNotExists",
      "ERCIRQoSDropBitsoutPerSecAlertState" : "true",
      "VPNGwBGPPeerStatusAlertSeverity" : "3",
      "VPNGwBGPPeerStatusWindowSize" : "PT5M",
      "VPNGwBGPPeerStatusEvaluationFrequency" : "PT5M",
      "VPNGwBGPPeerStatusPolicyEffect" : "deployIfNotExists",
      "VPNGwBGPPeerStatusAlertState" : "true",
      "VPNGwBGPPeerStatusThreshold" : "1",
      "VnetGwERCpuUtilAlertSeverity" : "3",
      "VnetGwERCpuUtilWindowSize" : "PT5M",
      "VnetGwERCpuUtilEvaluationFrequency" : "PT1M",
      "VnetGwERCpuUtilPolicyEffect" : "deployIfNotExists",
      "VnetGwERCpuUtilAlertState" : "true",
      "VnetGwERCpuUtilThreshold" : "80",
      "VnetGwTunnelBWAlertSeverity" : "0",
      "VnetGwTunnelBWWindowSize" : "PT5M",
      "VnetGwTunnelBWEvaluationFrequency" : "PT1M",
      "VnetGwTunnelBWPolicyEffect" : "deployIfNotExists",
      "VnetGwTunnelBWAlertState" : "true",
      "VnetGwTunnelBWThreshold" : "1",
      "VnetGwTunnelEgressAlertSeverity" : "0",
      "VnetGwTunnelEgressWindowSize" : "PT5M",
      "VnetGwTunnelEgressEvaluationFrequency" : "PT5M",
      "VnetGwTunnelEgressPolicyEffect" : "disabled",
      "VnetGwTunnelEgressAlertState" : "true",
      "VnetGwTunnelEgressThreshold" : "1",
      "VnetGwTunnelIngressAlertSeverity" : "0",
      "VnetGwTunnelIngressWindowSize" : "PT5M",
      "VnetGwTunnelIngressEvaluationFrequency" : "PT5M",
      "VnetGwTunnelIngressPolicyEffect" : "disabled",
      "VnetGwTunnelIngressAlertState" : "true",
      "VnetGwTunnelIngressThreshold" : "1",
      "VPNGWBandWidthUtilAlertSeverity" : "0",
      "VPNGWBandWidthUtilWindowSize" : "PT5M",
      "VPNGWBandWidthUtilEvaluationFrequency" : "PT5M",
      "VPNGWBandWidthUtilPolicyEffect" : "deployIfNotExists",
      "VPNGWBandWidthUtilAlertState" : "true",
      "VPNGWBandWidthUtilThreshold" : "1",
      "VPNGWEgressAlertSeverity" : "0",
      "VPNGWEgressWindowSize" : "PT5M",
      "VPNGWEgressEvaluationFrequency" : "PT5M",
      "VPNGWEgressPolicyEffect" : "disabled",
      "VPNGWEgressAlertState" : "true",
      "VPNGWEgressThreshold" : "1",
      "VPNGWTunnelEgressPacketDropCountAlertSeverity" : "3",
      "VPNGWTunnelEgressPacketDropCountWindowSize" : "PT5M",
      "VPNGWTunnelEgressPacketDropCountFrequency" : "PT5M",
      "VPNGWTunnelEgressPacketDropCountPolicyEffect" : "deployIfNotExists",
      "VPNGWTunnelEgressPacketDropCountAlertState" : "true",
      "VPNGWTunnelEgressPacketDropMismatchAlertSeverity" : "3",
      "VPNGWTunnelEgressPacketDropMismatchWindowSize" : "PT5M",
      "VPNGWTunnelEgressPacketDropMismatchFrequency" : "PT5M",
      "VPNGWTunnelEgressPacketDropMismatchPolicyEffect" : "deployIfNotExists",
      "VPNGWTunnelEgressPacketDropMismatchAlertState" : "true",
      "VPNGWIngressAlertSeverity" : "0",
      "VPNGWIngressWindowSize" : "PT5M",
      "VPNGWIngressEvaluationFrequency" : "PT5M",
      "VPNGWIngressPolicyEffect" : "disabled",
      "VPNGWIngressAlertState" : "true",
      "VPNGWIngressThreshold" : "1",
      "VPNGWIngressAutoMitigate" : "true",
      "VPNGWTunnelIngressPacketDropCountAlertSeverity" : "3",
      "VPNGWTunnelIngressPacketDropCountWindowSize" : "PT5M",
      "VPNGWTunnelIngressPacketDropCountFrequency" : "PT5M",
      "VPNGWTunnelIngressPacketDropCountPolicyEffect" : "deployIfNotExists",
      "VPNGWTunnelIngressPacketDropCountAlertState" : "true",
      "VPNGWTunnelIngressPacketDropMismatchAlertSeverity" : "3",
      "VPNGWTunnelIngressPacketDropMismatchWindowSize" : "PT5M",
      "VPNGWTunnelIngressPacketDropMismatchFrequency" : "PT5M",
      "VPNGWTunnelIngressPacketDropMismatchPolicyEffect" : "deployIfNotExists",
      "VPNGWTunnelIngressPacketDropMismatchAlertState" : "true",
      "PDNSZCapacityUtilAlertSeverity" : "2",
      "PDNSZCapacityUtilWindowSize" : "PT1H",
      "PDNSZCapacityUtilEvaluationFrequency" : "PT1H",
      "PDNSZCapacityUtilPolicyEffect" : "deployIfNotExists",
      "PDNSZCapacityUtilAlertState" : "true",
      "PDNSZCapacityUtilThreshold" : "80",
      "PDNSZQueryVolumeAlertSeverity" : "4",
      "PDNSZQueryVolumeWindowSize" : "PT1H",
      "PDNSZQueryVolumeEvaluationFrequency" : "PT1H",
      "PDNSZQueryVolumePolicyEffect" : "disabled",
      "PDNSZQueryVolumeAlertState" : "true",
      "PDNSZQueryVolumeThreshold" : "500",
      "PDNSZRecordSetCapacityAlertSeverity" : "2",
      "PDNSZRecordSetCapacityWindowSize" : "PT1H",
      "PDNSZRecordSetCapacityEvaluationFrequency" : "PT1H",
      "PDNSZRecordSetCapacityPolicyEffect" : "deployIfNotExists",
      "PDNSZRecordSetCapacityAlertState" : "true",
      "PDNSZRecordSetCapacityThreshold" : "80",
      "PDNSZRegistrationCapacityUtilAlertSeverity" : "2",
      "PDNSZRegistrationCapacityUtilWindowSize" : "PT1H",
      "PDNSZRegistrationCapacityUtilEvaluationFrequency" : "PT1H",
      "PDNSZRegistrationCapacityUtilPolicyEffect" : "deployIfNotExists",
      "PDNSZRegistrationCapacityUtilAlertState" : "true",
      "PDNSZRegistrationCapacityUtilThreshold" : "80",
      "PIPDDoSAttackAlertSeverity" : "1",
      "PIPDDoSAttackWindowSize" : "PT5M",
      "PIPDDoSAttackEvaluationFrequency" : "PT5M",
      "PIPDDoSAttackPolicyEffect" : "deployIfNotExists",
      "PIPDDoSAttackAlertState" : "true",
      "PIPDDoSAttackThreshold" : "0",
      "PIPPacketsInDDoSAlertSeverity" : "4",
      "PIPPacketsInDDoSWindowSize" : "PT5M",
      "PIPPacketsInDDoSEvaluationFrequency" : "PT5M",
      "PIPPacketsInDDoSPolicyEffect" : "disabled",
      "PIPPacketsInDDoSAlertState" : "true",
      "PIPPacketsInDDoSThreshold" : "40000",
      "PIPVIPAvailabilityAlertSeverity" : "1",
      "PIPVIPAvailabilityWindowSize" : "PT5M",
      "PIPVIPAvailabilityEvaluationFrequency" : "PT1M",
      "PIPVIPAvailabilityPolicyEffect" : "deployIfNotExists",
      "PIPVIPAvailabilityAlertState" : "true",
      "PIPVIPAvailabilityThreshold" : "1",
      "PIPBytesInDDoSAlertSeverity" : "4",
      "PIPBytesInDDoSWindowSize" : "PT5M",
      "PIPBytesInDDoSEvaluationFrequency" : "PT5M",
      "PIPBytesInDDoSPolicyEffect" : "disabled",
      "PIPBytesInDDoSAlertState" : "true",
      "PIPBytesInDDoSThreshold" : "8000000",
      "ERGwExpressRouteBitsInAlertSeverity" : "0",
      "ERGwExpressRouteBitsInWindowSize" : "PT5M",
      "ERGwExpressRouteBitsInEvaluationFrequency" : "PT5M",
      "ERGwExpressRouteBitsInPolicyEffect" : "disabled",
      "ERGwExpressRouteBitsInAlertState" : "true",
      "ERGwExpressRouteBitsInThreshold" : "1",
      "ERGwExpressRouteBitsOutAlertSeverity" : "0",
      "ERGwExpressRouteBitsOutWindowSize" : "PT5M",
      "ERGwExpressRouteBitsOutEvaluationFrequency" : "PT5M",
      "ERGwExpressRouteBitsOutPolicyEffect" : "disabled",
      "ERGwExpressRouteBitsOutAlertState" : "true",
      "ERGwExpressRouteBitsOutThreshold" : "1",
      "ERGwExpressRouteCpuUtilAlertSeverity" : "1",
      "ERGwExpressRouteCpuUtilWindowSize" : "PT5M",
      "ERGwExpressRouteCpuUtilEvaluationFrequency" : "PT1M",
      "ERGwExpressRouteCpuUtilPolicyEffect" : "deployIfNotExists",
      "ERGwExpressRouteCpuUtilAlertState" : "true",
      "ERGwExpressRouteCpuUtilThreshold" : "80",
      "VNETDDOSAttackAlertSeverity" : "1",
      "VNETDDOSAttackWindowSize" : "PT5M",
      "VNETDDOSAttackEvaluationFrequency" : "PT1M",
      "VNETDDOSAttackPolicyEffect" : "deployIfNotExists",
      "VNETDDOSAttackAlertState" : "true",
      "VNETDDOSAttackThreshold" : "1",
      "VnetGwTunnelEgressPacketDropCountAlertSeverity" : "1",
      "VnetGwTunnelEgressPacketDropCountWindowSize" : "PT5M",
      "VnetGwTunnelEgressPacketDropCountEvaluationFrequency" : "PT5M",
      "VnetGwTunnelEgressPacketDropCountPolicyEffect" : "deployIfNotExists",
      "VnetGwTunnelEgressPacketDropCountAlertState" : "true",
      "VnetGwTunnelEgressPacketDropMismatchAlertSeverity" : "3",
      "VnetGwTunnelEgressPacketDropMismatchWindowSize" : "PT5M",
      "VnetGwTunnelEgressPacketDropMismatchEvaluationFrequency" : "PT5M",
      "VnetGwTunnelEgressPacketDropMismatchPolicyEffect" : "deployIfNotExists",
      "VnetGwTunnelEgressPacketDropMismatchAlertState" : "true",
      "VnetGwExpressRouteBitsPerSecondAlertSeverity" : "0",
      "VnetGwExpressRouteBitsPerSecondWindowSize" : "PT5M",
      "VnetGwExpressRouteBitsPerSecondEvaluationFrequency" : "PT1M",
      "VnetGwExpressRouteBitsPerSecondPolicyEffect" : "deployIfNotExists",
      "VnetGwExpressRouteBitsPerSecondAlertState" : "true",
      "VnetGwExpressRouteBitsPerSecondThreshold" : "1",
      "VnetGwTunnelIngressPacketDropMismatchAlertSeverity" : "3",
      "VnetGwTunnelIngressPacketDropMismatchWindowSize" : "PT5M",
      "VnetGwTunnelIngressPacketDropMismatchEvaluationFrequency" : "PT5M",
      "VnetGwTunnelIngressPacketDropMismatchPolicyEffect" : "deployIfNotExists",
      "VnetGwTunnelIngressPacketDropMismatchAlertState" : "true",
      "VnetGwTunnelIngressPacketDropCountAlertSeverity" : "3",
      "VnetGwTunnelIngressPacketDropCountWindowSize" : "PT5M",
      "VnetGwTunnelIngressPacketDropCountEvaluationFrequency" : "PT5M",
      "VnetGwTunnelIngressPacketDropCountPolicyEffect" : "deployIfNotExists",
      "VnetGwTunnelIngressPacketDropCountAlertState" : "true",
      "ERCIRBgpAvailabilityAlertSeverity" : "0",
      "ERCIRBgpAvailabilityWindowSize" : "PT5M",
      "ERCIRBgpAvailabilityEvaluationFrequency" : "PT1M",
      "ERCIRBgpAvailabilityPolicyEffect" : "deployIfNotExists",
      "ERCIRBgpAvailabilityAlertState" : "true",
      "ERCIRBgpAvailabilityThreshold" : "90",
      "ERCIRArpAvailabilityAlertSeverity" : "0",
      "ERCIRArpAvailabilityWindowSize" : "PT5M",
      "ERCIRArpAvailabilityFrequency" : "PT1M",
      "ERCIRArpAvailabilityPolicyEffect" : "deployIfNotExists",
      "ERCIRArpAvailabilityAlertState" : "true",
      "ERCIRArpAvailabilityThreshold" : "90",
      "AFWSNATPortUtilizationAlertSeverity" : "1",
      "AFWSNATPortUtilizationWindowSize" : "PT5M",
      "AFWSNATPortUtilizationFrequency" : "PT1M",
      "AFWSNATPortUtilizationPolicyEffect" : "deployIfNotExists",
      "AFWSNATPortUtilizationAlertState" : "true",
      "AFWSNATPortUtilizationThreshold" : "80",
      "FirewallHealthAlertSeverity" : "0",
      "FirewallHealthWindowSize" : "PT5M",
      "FirewallHealthEvaluationFrequency" : "PT1M",
      "FirewallHealthPolicyEffect" : "deployIfNotExists",
      "FirewallHealthAlertState" : "true",
      "FirewallHealthThreshold" : "90",
      "activityFWDeleteAlertState" : "true",
      "activityNSGDeleteAlertState" : "true",
      "activityUDRUpdateAlertState" : "true",
      "activityVPNGWDeleteAlertState" : "true",
      "LBDatapathAvailabilityAlertSeverity" : "0",
      "LBDatapathAvailabilityWindowSize" : "PT5M",
      "LBDatapathAvailabilityEvaluationFrequency" : "PT1M",
      "LBDatapathAvailabilityPolicyEffect" : "deployIfNotExists",
      "LBDatapathAvailabilityAlertState" : "true",
      "LBGlobalBackendAvailabilityAlertSeverity" : "0",
      "LBGlobalBackendAvailabilityWindowSize" : "PT5M",
      "LBGlobalBackendAvailabilityEvaluationFrequency" : "PT1M",
      "LBGlobalBackendAvailabilityPolicyEffect" : "deployIfNotExists",
      "LBGlobalBackendAvailabilityAlertState" : "true",
      "LBHealthProbeStatusAlertSeverity" : "2",
      "LBHealthProbeStatusWindowSize" : "PT5M",
      "LBHealthProbeStatusEvaluationFrequency" : "PT1M",
      "LBHealthProbeStatusPolicyEffect" : "deployIfNotExists",
      "LBHealthProbeStatusAlertState" : "true",
      "LBUsedSNATPortsAlertSeverity" : "1",
      "LBUsedSNATPortsWindowSize" : "PT5M",
      "LBUsedSNATPortsEvaluationFrequency" : "PT1M",
      "LBUsedSNATPortsPolicyEffect" : "deployIfNotExists",
      "LBUsedSNATPortsAlertState" : "true",
      "ERPBitsInPerSecondAlertSeverity" : "0",
      "ERPBitsInPerSecondWindowSize" : "PT5M",
      "ERPBitsInPerSecondEvaluationFrequency" : "PT1M",
      "ERPBitsInPerSecondPolicyEffect" : "deployIfNotExists",
      "ERPBitsInPerSecondAlertState" : "true",
      "ERPBitsOutPerSecondAlertSeverity" : "0",
      "ERPBitsOutPerSecondWindowSize" : "PT5M",
      "ERPBitsOutPerSecondEvaluationFrequency" : "PT1M",
      "ERPBitsOutPerSecondPolicyEffect" : "deployIfNotExists",
      "ERPBitsOutPerSecondAlertState" : "true",
      "ERPLineProtocolAlertSeverity" : "0",
      "ERPLineProtocolWindowSize" : "PT5M",
      "ERPLineProtocolEvaluationFrequency" : "PT1M",
      "ERPLineProtocolPolicyEffect" : "deployIfNotExists",
      "ERPLineProtocolAlertState" : "true",
      "ERPRxLightLevelHighAlertSeverity" : "1",
      "ERPRxLightLevelHighWindowSize" : "PT5M",
      "ERPRxLightLevelHighEvaluationFrequency" : "PT1M",
      "ERPRxLightLevelHighPolicyEffect" : "deployIfNotExists",
      "ERPRxLightLevelHighAlertState" : "true",
      "ERPRxLightLevelLowAlertSeverity" : "1",
      "ERPRxLightLevelLowWindowSize" : "PT5M",
      "ERPRxLightLevelLowEvaluationFrequency" : "PT1M",
      "ERPRxLightLevelLowPolicyEffect" : "deployIfNotExists",
      "ERPRxLightLevelLowAlertState" : "true",
      "ERPTxLightLevelHighAlertSeverity" : "1",
      "ERPTxLightLevelHighWindowSize" : "PT5M",
      "ERPTxLightLevelHighEvaluationFrequency" : "PT1M",
      "ERPTxLightLevelHighPolicyEffect" : "deployIfNotExists",
      "ERPTxLightLevelHighAlertState" : "true",
      "ERPTxLightLevelLowAlertSeverity" : "1",
      "ERPTxLightLevelLowWindowSize" : "PT5M",
      "ERPTxLightLevelLowEvaluationFrequency" : "PT1M",
      "ERPTxLightLevelLowPolicyEffect" : "deployIfNotExists",
      "ERPTxLightLevelLowAlertState" : "true"
    },
    "Deploy-AMBA-LandingZone" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "KVRequestAlertSeverity" : "2",
      "KVRequestWindowSize" : "PT5M",
      "KVRequestEvaluationFrequency" : "PT5M",
      "KVRequestPolicyEffect" : "disabled",
      "KVRequestAlertState" : "true",
      "KvAvailabilityAlertSeverity" : "1",
      "KvAvailabilityWindowSize" : "PT1M",
      "KvAvailabilityEvaluationFrequency" : "PT1M",
      "KvAvailabilityPolicyEffect" : "disabled",
      "KvAvailabilityAlertState" : "true",
      "KVAvailabilityThreshold" : "20",
      "KvLatencyAvailabilityAlertSeverity" : "3",
      "KvLatencyAvailabilityWindowSize" : "PT5M",
      "KvLatencyAvailabilityEvaluationFrequency" : "PT5M",
      "KvLatencyAvailabilityPolicyEffect" : "disabled",
      "KvLatencyAvailabilityAlertState" : "true",
      "KvLatencyAvailabilityThreshold" : "1000",
      "KVCapacityAlertSeverity" : "1",
      "KVCapacityWindowSize" : "PT5M",
      "KVCapacityEvaluationFrequency" : "PT1M",
      "KVCapacityPolicyEffect" : "disabled",
      "KVCapacityAlertState" : "true",
      "KVCapacityThreshold" : "75",
      "activityKVDeleteAlertState" : "true",
      "StorageAccountAvailabilityAlertSeverity" : "1",
      "StorageAccountAvailabilityWindowSize" : "PT5M",
      "StorageAccountAvailabilityFrequency" : "PT5M",
      "StorageAccountAvailabilityPolicyEffect" : "deployIfNotExists",
      "StorageAccountAvailabilityAlertState" : "true",
      "StorageAccountAvailabilityThreshold" : "90",
      "StorageAccountDeletePolicyEffect" : "deployIfNotExists",
      "StorageAccountDeleteAlertState" : "true",
      "PIPDDoSAttackAlertSeverity" : "1",
      "PIPDDoSAttackWindowSize" : "PT5M",
      "PIPDDoSAttackEvaluationFrequency" : "PT5M",
      "PIPDDoSAttackPolicyEffect" : "deployIfNotExists",
      "PIPDDoSAttackAlertState" : "true",
      "PIPDDoSAttackThreshold" : "0",
      "PIPPacketsInDDoSAlertSeverity" : "4",
      "PIPPacketsInDDoSWindowSize" : "PT5M",
      "PIPPacketsInDDoSEvaluationFrequency" : "PT5M",
      "PIPPacketsInDDoSPolicyEffect" : "disabled",
      "PIPPacketsInDDoSAlertState" : "true",
      "PIPPacketsInDDoSThreshold" : "40000",
      "PIPVIPAvailabilityAlertSeverity" : "1",
      "PIPVIPAvailabilityWindowSize" : "PT5M",
      "PIPVIPAvailabilityEvaluationFrequency" : "PT1M",
      "PIPVIPAvailabilityPolicyEffect" : "deployIfNotExists",
      "PIPVIPAvailabilityAlertState" : "true",
      "PIPVIPAvailabilityThreshold" : "1",
      "PIPBytesInDDoSAlertSeverity" : "4",
      "PIPBytesInDDoSWindowSize" : "PT5M",
      "PIPBytesInDDoSEvaluationFrequency" : "PT5M",
      "PIPBytesInDDoSPolicyEffect" : "disabled",
      "PIPBytesInDDoSAlertState" : "true",
      "PIPBytesInDDoSThreshold" : "8000000",
      "RVBackupHealthMonitorPolicyEffect" : "modify",
      "VNETDDOSAttackAlertSeverity" : "1",
      "VNETDDOSAttackWindowSize" : "PT5M",
      "VNETDDOSAttackEvaluationFrequency" : "PT1M",
      "VNETDDOSAttackPolicyEffect" : "deployIfNotExists",
      "VNETDDOSAttackAlertState" : "true",
      "VNETDDOSAttackThreshold" : "1",
      "activityNSGDeleteAlertState" : "true",
      "activityUDRUpdateAlertState" : "true",
      "VMHeartBeatRGAlertSeverity" : "1",
      "VMHeartBeatRGWindowSize" : "PT15M",
      "VMHeartBeatRGEvaluationFrequency" : "PT5M",
      "VMHeartBeatRGAutoMitigate" : "true",
      "VMHeartBeatRGAutoResolve" : "true",
      "VMHeartBeatRGAutoResolveTime" : "00:10:00",
      "VMHeartBeatRGPolicyEffect" : "deployIfNotExists",
      "VMHeartBeatRGAlertState" : "true",
      "VMHeartBeatRGThreshold" : "10",
      "VMHeartBeatRGOperator" : "GreaterThan",
      "VMHeartBeatRGTimeAggregation" : "Average",
      "VMNetworkInAlertSeverity" : "2",
      "VMNetworkInWindowSize" : "PT15M",
      "VMNetworkInEvaluationFrequency" : "PT5M",
      "VMNetworkInAutoMitigate" : "true",
      "VMNetworkInAutoResolve" : "true",
      "VMNetworkInAutoResolveTime" : "00:10:00",
      "VMNetworkInPolicyEffect" : "deployIfNotExists",
      "VMNetworkInAlertState" : "true",
      "VMNetworkInThreshold" : "10000000",
      "VMNetworkInOperator" : "GreaterThan",
      "VMNetworkInTimeAggregation" : "Average",
      "VMNetworkInEvaluationPeriods" : "1",
      "VMNetworkInFailingPeriods" : "1",
      "VMNetworkInComputersToInclude" : [
        "*"
      ],
      "VMNetworkInNetworkInterfaceToInclude" : [
        "*"
      ],
      "VMNetworkOutAlertSeverity" : "2",
      "VMNetworkOutWindowSize" : "PT15M",
      "VMNetworkOutEvaluationFrequency" : "PT5M",
      "VMNetworkOutAutoMitigate" : "true",
      "VMNetworkOutAutoResolve" : "true",
      "VMNetworkOutAutoResolveTime" : "00:10:00",
      "VMNetworkOutPolicyEffect" : "deployIfNotExists",
      "VMNetworkOutAlertState" : "true",
      "VMNetworkOutThreshold" : "10000000",
      "VMNetworkOutOperator" : "GreaterThan",
      "VMNetworkOutTimeAggregation" : "Average",
      "VMNetworkOutEvaluationPeriods" : "1",
      "VMNetworkOutFailingPeriods" : "1",
      "VMNetworkOutComputersToInclude" : [
        "*"
      ],
      "VMNetworkOutNetworkInterfaceToInclude" : [
        "*"
      ],
      "VMOSDiskReadLatencyAlertSeverity" : "2",
      "VMOSDiskReadLatencyWindowSize" : "PT15M",
      "VMOSDiskReadLatencyEvaluationFrequency" : "PT5M",
      "VMOSDiskReadLatencyAutoMitigate" : "true",
      "VMOSDiskReadLatencyAutoResolve" : "true",
      "VMOSDiskReadLatencyAutoResolveTime" : "00:10:00",
      "VMOSDiskReadLatencyPolicyEffect" : "deployIfNotExists",
      "VMOSDiskReadLatencyAlertState" : "true",
      "VMOSDiskReadLatencyThreshold" : "30",
      "VMOSDiskReadLatencyOperator" : "LessThan",
      "VMOSDiskReadLatencyTimeAggregation" : "Average",
      "VMOSDiskReadLatencyEvaluationPeriods" : "1",
      "VMOSDiskReadLatencyFailingPeriods" : "1",
      "VMOSDiskReadLatencyComputersToInclude" : [
        "*"
      ],
      "VMOSDiskReadLatencyDisksToInclude" : [
        "C:",
        "/"
      ],
      "VMOSDiskWriteLatencyAlertSeverity" : "2",
      "VMOSDiskWriteLatencyWindowSize" : "PT15M",
      "VMOSDiskWriteLatencyEvaluationFrequency" : "PT5M",
      "VMOSDiskWriteLatencyAutoMitigate" : "true",
      "VMOSDiskWriteLatencyAutoResolve" : "true",
      "VMOSDiskWriteLatencyAutoResolveTime" : "00:10:00",
      "VMOSDiskWriteLatencyPolicyEffect" : "deployIfNotExists",
      "VMOSDiskWriteLatencyAlertState" : "true",
      "VMOSDiskWriteLatencyThreshold" : "50",
      "VMOSDiskWriteLatencyOperator" : "LessThan",
      "VMOSDiskWriteLatencyTimeAggregation" : "Average",
      "VMOSDiskWriteLatencyEvaluationPeriods" : "1",
      "VMOSDiskWriteLatencyFailingPeriods" : "1",
      "VMOSDiskWriteLatencyComputersToInclude" : [
        "*"
      ],
      "VMOSDiskWriteLatencyDisksToInclude" : [
        "C:",
        "/"
      ],
      "VMOSDiskSpaceAlertSeverity" : "2",
      "VMOSDiskSpaceWindowSize" : "PT15M",
      "VMOSDiskSpaceEvaluationFrequency" : "PT5M",
      "VMOSDiskSpaceAutoMitigate" : "true",
      "VMOSDiskSpaceAutoResolve" : "true",
      "VMOSDiskSpaceAutoResolveTime" : "00:10:00",
      "VMOSDiskSpacePolicyEffect" : "deployIfNotExists",
      "VMOSDiskSpaceAlertState" : "true",
      "VMOSDiskSpaceThreshold" : "10",
      "VMOSDiskSpaceOperator" : "LessThan",
      "VMOSDiskSpaceTimeAggregation" : "Average",
      "VMOSDiskSpaceEvaluationPeriods" : "1",
      "VMOSDiskSpaceFailingPeriods" : "1",
      "VMOSDiskSpaceComputersToInclude" : [
        "*"
      ],
      "VMOSDiskSpaceDisksToInclude" : [
        "C:",
        "/"
      ],
      "VMPercentCPUAlertSeverity" : "2",
      "VMPercentCPUWindowSize" : "PT15M",
      "VMPercentCPUEvaluationFrequency" : "PT5M",
      "VMPercentCPUAutoMitigate" : "true",
      "VMPercentCPUAutoResolve" : "true",
      "VMPercentCPUAutoResolveTime" : "00:10:00",
      "VMPercentCPUPolicyEffect" : "deployIfNotExists",
      "VMPercentCPUAlertState" : "true",
      "VMPercentCPUThreshold" : "85",
      "VMPercentCPUOperator" : "GreaterThan",
      "VMPercentCPUTimeAggregation" : "Average",
      "VMPercentMemoryAlertSeverity" : "2",
      "VMPercentMemoryWindowSize" : "PT15M",
      "VMPercentMemoryEvaluationFrequency" : "PT5M",
      "VMPercentMemoryAutoMitigate" : "true",
      "VMPercentMemoryAutoResolve" : "true",
      "VMPercentMemoryAutoResolveTime" : "00:10:00",
      "VMPercentMemoryPolicyEffect" : "deployIfNotExists",
      "VMPercentMemoryAlertState" : "true",
      "VMPercentMemoryThreshold" : "10",
      "VMPercentMemoryOperator" : "LessThan",
      "VMPercentMemoryTimeAggregation" : "Average",
      "VMDataDiskSpaceAlertSeverity" : "2",
      "VMDataDiskSpaceWindowSize" : "PT15M",
      "VMDataDiskSpaceEvaluationFrequency" : "PT5M",
      "VMDataDiskSpaceAutoMitigate" : "true",
      "VMDataDiskSpaceAutoResolve" : "true",
      "VMDataDiskSpaceAutoResolveTime" : "00:10:00",
      "VMDataDiskSpacePolicyEffect" : "deployIfNotExists",
      "VMDataDiskSpaceAlertState" : "true",
      "VMDataDiskSpaceThreshold" : "10",
      "VMDataDiskSpaceOperator" : "LessThan",
      "VMDataDiskSpaceTimeAggregation" : "Average",
      "VMDataDiskSpaceEvaluationPeriods" : "1",
      "VMDataDiskSpaceFailingPeriods" : "1",
      "VMDataDiskSpaceDisksToInclude" : [
        "*"
      ],
      "VMDataDiskReadLatencyAlertSeverity" : "2",
      "VMDataDiskReadLatencyWindowSize" : "PT15M",
      "VMDataDiskReadLatencyEvaluationFrequency" : "PT5M",
      "VMDataDiskReadLatencyAutoMitigate" : "true",
      "VMDataDiskReadLatencyAutoResolve" : "true",
      "VMDataDiskReadLatencyAutoResolveTime" : "00:10:00",
      "VMDataDiskReadLatencyPolicyEffect" : "deployIfNotExists",
      "VMDataDiskReadLatencyAlertState" : "true",
      "VMDataDiskReadLatencyThreshold" : "30",
      "VMDataDiskReadLatencyOperator" : "LessThan",
      "VMDataDiskReadLatencyTimeAggregation" : "Average",
      "VMDataDiskReadLatencyEvaluationPeriods" : "1",
      "VMDataDiskReadLatencyFailingPeriods" : "1",
      "VMDataDiskReadLatencyComputersToInclude" : [
        "*"
      ],
      "VMDataDiskReadLatencyDisksToInclude" : [
        "*"
      ],
      "VMDataDiskWriteLatencyAlertSeverity" : "2",
      "VMDataDiskWriteLatencyWindowSize" : "PT15M",
      "VMDataDiskWriteLatencyEvaluationFrequency" : "PT5M",
      "VMDataDiskWriteLatencyAutoMitigate" : "true",
      "VMDataDiskWriteLatencyAutoResolve" : "true",
      "VMDataDiskWriteLatencyAutoResolveTime" : "00:10:00",
      "VMDataDiskWriteLatencyPolicyEffect" : "deployIfNotExists",
      "VMDataDiskWriteLatencyAlertState" : "true",
      "VMDataDiskWriteLatencyThreshold" : "30",
      "VMDataDiskWriteLatencyOperator" : "LessThan",
      "VMDataDiskWriteLatencyTimeAggregation" : "Average",
      "VMDataDiskWriteLatencyEvaluationPeriods" : "1",
      "VMDataDiskWriteLatencyFailingPeriods" : "1",
      "VMDataDiskWriteLatencyComputersToInclude" : [
        "*"
      ],
      "VMDataDiskWriteLatencyDisksToInclude" : [
        "*"
      ],
      "AGWApplicationGatewayTotalTimeAlertSeverity" : "2",
      "AGWApplicationGatewayTotalTimeWindowSize" : "PT5M",
      "AGWApplicationGatewayTotalTimeEvaluationFrequency" : "PT1M",
      "AGWApplicationGatewayTotalTimePolicyEffect" : "deployIfNotExists",
      "AGWApplicationGatewayTotalTimeAlertState" : "true",
      "AGWBackendLastByteResponseTimeAlertSeverity" : "2",
      "AGWBackendLastByteResponseTimeWindowSize" : "PT5M",
      "AGWBackendLastByteResponseTimeEvaluationFrequency" : "PT1M",
      "AGWBackendLastByteResponseTimePolicyEffect" : "deployIfNotExists",
      "AGWBackendLastByteResponseTimeAlertState" : "true",
      "AGWCapacityUnitsAlertSeverity" : "2",
      "AGWCapacityUnitsWindowSize" : "PT5M",
      "AGWCapacityUnitsEvaluationFrequency" : "PT1M",
      "AGWCapacityUnitsPolicyEffect" : "deployIfNotExists",
      "AGWCapacityUnitsAlertState" : "true",
      "AGWComputeUnitsAlertSeverity" : "2",
      "AGWComputeUnitsWindowSize" : "PT5M",
      "AGWComputeUnitsEvaluationFrequency" : "PT1M",
      "AGWComputeUnitsPolicyEffect" : "deployIfNotExists",
      "AGWComputeUnitsAlertState" : "true",
      "AGWCPUUtilAlertSeverity" : "2",
      "AGWCPUUtilWindowSize" : "PT5M",
      "AGWCPUUtilEvaluationFrequency" : "PT1M",
      "AGWCPUUtilPolicyEffect" : "deployIfNotExists",
      "AGWCPUUtilAlertState" : "true",
      "AGWFailedRequestsAlertSeverity" : "2",
      "AGWFailedRequestsWindowSize" : "PT5M",
      "AGWFailedRequestsEvaluationFrequency" : "PT1M",
      "AGWFailedRequestsPolicyEffect" : "deployIfNotExists",
      "AGWFailedRequestsAlertState" : "true",
      "AGWResponseStatusAlertSeverity" : "2",
      "AGWResponseStatusWindowSize" : "PT5M",
      "AGWResponseStatusEvaluationFrequency" : "PT1M",
      "AGWResponseStatusPolicyEffect" : "deployIfNotExists",
      "AGWResponseStatusAlertState" : "true",
      "AGWUnhealthyHostCountAlertSeverity" : "2",
      "AGWUnhealthyHostCountWindowSize" : "PT5M",
      "AGWUnhealthyHostCountEvaluationFrequency" : "PT1M",
      "AGWUnhealthyHostCountPolicyEffect" : "deployIfNotExists",
      "AGWUnhealthyHostCountAlertState" : "true",
      "LBDatapathAvailabilityAlertSeverity" : "0",
      "LBDatapathAvailabilityWindowSize" : "PT5M",
      "LBDatapathAvailabilityEvaluationFrequency" : "PT1M",
      "LBDatapathAvailabilityPolicyEffect" : "deployIfNotExists",
      "LBDatapathAvailabilityAlertState" : "true",
      "LBGlobalBackendAvailabilityAlertSeverity" : "0",
      "LBGlobalBackendAvailabilityWindowSize" : "PT5M",
      "LBGlobalBackendAvailabilityEvaluationFrequency" : "PT1M",
      "LBGlobalBackendAvailabilityPolicyEffect" : "deployIfNotExists",
      "LBGlobalBackendAvailabilityAlertState" : "true",
      "LBHealthProbeStatusAlertSeverity" : "2",
      "LBHealthProbeStatusWindowSize" : "PT5M",
      "LBHealthProbeStatusEvaluationFrequency" : "PT1M",
      "LBHealthProbeStatusPolicyEffect" : "deployIfNotExists",
      "LBHealthProbeStatusAlertState" : "true",
      "LBUsedSNATPortsAlertSeverity" : "1",
      "LBUsedSNATPortsWindowSize" : "PT5M",
      "LBUsedSNATPortsEvaluationFrequency" : "PT1M",
      "LBUsedSNATPortsPolicyEffect" : "deployIfNotExists",
      "LBUsedSNATPortsAlertState" : "true",
      "CDNPOriginHealthPercentageAlertSeverity" : "2",
      "CDNPOriginHealthPercentageWindowSize" : "PT5M",
      "CDNPOriginHealthPercentageEvaluationFrequency" : "PT1M",
      "CDNPOriginHealthPercentagePolicyEffect" : "deployIfNotExists",
      "CDNPOriginHealthPercentageAlertState" : "true",
      "CDNPOriginLatencyAlertSeverity" : "2",
      "CDNPOriginLatencyWindowSize" : "PT5M",
      "CDNPOriginLatencyEvaluationFrequency" : "PT1M",
      "CDNPOriginLatencyPolicyEffect" : "disabled",
      "CDNPOriginLatencyAlertState" : "true",
      "CDNPPercentage4XXAlertSeverity" : "2",
      "CDNPPercentage4XXWindowSize" : "PT5M",
      "CDNPPercentage4XXEvaluationFrequency" : "PT1M",
      "CDNPPercentage4XXPolicyEffect" : "deployIfNotExists",
      "CDNPPercentage4XXAlertState" : "true",
      "CDNPPercentage5XXAlertSeverity" : "2",
      "CDNPPercentage5XXWindowSize" : "PT5M",
      "CDNPPercentage5XXEvaluationFrequency" : "PT1M",
      "CDNPPercentage5XXPolicyEffect" : "deployIfNotExists",
      "CDNPPercentage5XXAlertState" : "true",
      "TMEndpointHealthAlertSeverity" : "2",
      "TMEndpointHealthWindowSize" : "PT5M",
      "TMEndpointHealthEvaluationFrequency" : "PT1M",
      "TMEndpointHealthPolicyEffect" : "deployIfNotExists",
      "TMEndpointHealthAlertState" : "true",
      "WSFCPUPercentageAlertSeverity" : "2",
      "WSFCPUPercentageWindowSize" : "PT5M",
      "WSFCPUPercentageEvaluationFrequency" : "PT1M",
      "WSFCPUPercentagePolicyEffect" : "deployIfNotExists",
      "WSFCPUPercentageAlertState" : "true",
      "WSFMemoryPercentageAlertSeverity" : "2",
      "WSFMemoryPercentageWindowSize" : "PT5M",
      "WSFMemoryPercentageEvaluationFrequency" : "PT1M",
      "WSFMemoryPercentagePolicyEffect" : "deployIfNotExists",
      "WSFMemoryPercentageAlertState" : "true",
      "WSFDiskQueueLengthAlertSeverity" : "2",
      "WSFDiskQueueLengthWindowSize" : "PT5M",
      "WSFDiskQueueLengthEvaluationFrequency" : "PT1M",
      "WSFDiskQueueLengthPolicyEffect" : "deployIfNotExists",
      "WSFDiskQueueLengthAlertState" : "true",
      "WSFHttpQueueLengthAlertSeverity" : "2",
      "WSFHttpQueueLengthWindowSize" : "PT5M",
      "WSFHttpQueueLengthEvaluationFrequency" : "PT1M",
      "WSFHttpQueueLengthPolicyEffect" : "deployIfNotExists",
      "WSFHttpQueueLengthAlertState" : "true",
      "FDBackendHealthAlertSeverity" : "2",
      "FDBackendHealthWindowSize" : "PT5M",
      "FDBackendHealthEvaluationFrequency" : "PT1M",
      "FDBackendHealthPolicyEffect" : "deployIfNotExists",
      "FDBackendHealthAlertState" : "true",
      "FDBackendRequestLatencyAlertSeverity" : "2",
      "FDBackendRequestLatencyWindowSize" : "PT5M",
      "FDBackendRequestLatencyEvaluationFrequency" : "PT1M",
      "FDBackendRequestLatencyPolicyEffect" : "deployIfNotExists",
      "FDBackendRequestLatencyAlertState" : "true"
    },
    "Deploy-AMBA-Notification" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "ALZMonitorActionGroupEmail" : "",
      "ALZLogicappResourceId" : "",
      "ALZLogicappCallbackUrl" : "",
      "ALZArmRoleId" : "",
      "ALZEventHubResourceId" : "",
      "ALZWebhookServiceUri" : "",
      "ALZFunctionResourceId" : "",
      "ALZFunctionTriggerUrl" : "",
      "BYOActionGroup" : "",
      "BYOAlertProcessingRule" : ""
    },
    "Deploy-AMBA-Identity" : {
      "ALZMonitorResourceGroupName" : "rg-amba-monitoring-001",
      "ALZMonitorResourceGroupTags" : {
        "_deployed_by_alz_monitor" : true,
        "_deployed_by_terraform" : true
      },
      "ALZMonitorResourceGroupLocation" : "germanywestcentral",
      "KVRequestAlertSeverity" : "2",
      "KVRequestWindowSize" : "PT5M",
      "KVRequestEvaluationFrequency" : "PT5M",
      "KVRequestPolicyEffect" : "disabled",
      "KVRequestAlertState" : "true",
      "KvAvailabilityAlertSeverity" : "1",
      "KvAvailabilityWindowSize" : "PT1M",
      "KvAvailabilityEvaluationFrequency" : "PT1M",
      "KvAvailabilityPolicyEffect" : "disabled",
      "KvAvailabilityAlertState" : "true",
      "KVAvailabilityThreshold" : "20",
      "KvLatencyAvailabilityAlertSeverity" : "3",
      "KvLatencyAvailabilityWindowSize" : "PT5M",
      "KvLatencyAvailabilityEvaluationFrequency" : "PT5M",
      "KvLatencyAvailabilityPolicyEffect" : "disabled",
      "KvLatencyAvailabilityAlertState" : "true",
      "KvLatencyAvailabilityThreshold" : "1000",
      "KVCapacityAlertSeverity" : "1",
      "KVCapacityWindowSize" : "PT5M",
      "KVCapacityEvaluationFrequency" : "PT1M",
      "KVCapacityPolicyEffect" : "disabled",
      "KVCapacityAlertState" : "true",
      "KVCapacityThreshold" : "75",
      "activityKVDeleteAlertState" : "true"
    }
  }
}
